### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by MoonMoon82** [laksjdjf/pfg-ComfyUI#1]
Hi!
I get this error message when I try to run the PFG node:

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\pfg-ComfyUI\pfg.py", line 69, in add_pfg
    pfg_cond = pfg_cond.reshape(1, -1, cond.shape[2])
RuntimeError: shape '[1, -1, 768]' is invalid for input of size 10240
```

Any idea?

**Comment by laksjdjf** [comment]
You seem to be using a model for SDV2.

[IP-Adapter](https://github.com/laksjdjf/IPAdapter-ComfyUI) are more powerful and can be used with a variety of models.

**Comment by MoonMoon82** [comment]
@laksjdjf Thank you for your feedback! The right model for SD1.5 solved this issue.
